config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plans
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :chargeable, polymorphic: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :plan
end

app/models/lodging.rb
class Lodging < Event
  belongs_to :plan
end

app/models/meal.rb
class Meal < Event
  belongs_to :plan
end

app/models/other.rb
class Other < Event
  belongs_to :plan
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :events, dependent: :destroy # イベントとの関連付け

  def events_by_date
    (start_date..end_date).each_with_object({}) do |date, hash|
      hash[date] = events.where(date: date)
    end
  end
end

app/models/sightseeing.rb
class Sightseeing < Event
  belongs_to :plan
end

app/models/transit.rb
class Transit < Event
  belongs_to :plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_plan
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /plans/:plan_id/events
  def index
    @events = @plan.events
  end

  # GET /plans/:plan_id/events/new
  def new
    @event = @plan.events.new
  end

  # POST /plans/:plan_id/events
  def create
    @event = @plan.events.new(event_params)

    if @event.save
      redirect_to plan_events_path(@plan), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # GET /plans/:plan_id/events/:id
  def show
  end

  # GET /plans/:plan_id/events/:id/edit
  def edit
  end

  # PATCH/PUT /plans/:plan_id/events/:id
  def update
    if @event.update(event_params)
      redirect_to plan_event_path(@plan, @event), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /plans/:plan_id/events/:id
  def destroy
    @event.destroy
    redirect_to plan_events_path(@plan), notice: 'Event was successfully destroyed.'
  end

  private

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def set_event
    @event = @plan.events.find(params[:id])
  end

  # app/controllers/events_controller.rb
  def event_params
    params.require(:event).permit(:name, :start_time, :end_time, :location, :description, :event_type, :date) # dateを追加
  end

end

app/controllers/plans_controller.rb
# app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_plan
    @plan = Plan.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def plan_params
    params.require(:plan).permit(:title, :start_date, :end_date, :description) # 必要なパラメータを追加
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/events/edit.html.erb
<!-- app/views/events/edit.html.erb -->
<h1>Edit Event for <%= @plan.name %></h1>
<%= form_with(model: [@plan, @event], local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :date %>
    <%= form.date_select :date, selected: @event.date %>
  </div>
  <div>
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>
  <div>
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>
  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :event_type %>
    <%= form.select :event_type, ['Lodging', 'Sightseeing', 'Transit', 'Meal', 'Other'], selected: @event.event_type %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', plan_events_path(@plan) %>

app/views/events/index.html.erb
<!-- app/views/events/index.html.erb -->
<h1>Events for <%= @plan.name %></h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Location</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= event.end_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
        <td>
          <%= link_to 'Show', plan_event_path(@plan, event) %>
          <%= link_to 'Edit', edit_plan_event_path(@plan, event) %>
          <%= link_to 'Destroy', plan_event_path(@plan, event), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Event', new_plan_event_path(@plan) %>
<%= link_to 'Back', plans_path %>

app/views/events/new.html.erb
<!-- app/views/events/new.html.erb -->
<h1>New Event for <%= @plan.name %></h1>
<%= form_with(model: [@plan, @event], local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>
  <div>
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>
  <div>
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>
  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :event_type %>
    <%= form.select :event_type, ['Lodging', 'Sightseeing', 'Transit', 'Meal', 'Other'] %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', plan_events_path(@plan) %>

app/views/events/show.html.erb
<!-- app/views/events/show.html.erb -->
<h1>Event Details</h1>
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>
<p>
  <strong>Start Time:</strong>
  <%= @event.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>
<p>
  <strong>End Time:</strong>
  <%= @event.end_time.strftime("%Y-%m-%d %H:%M") %>
</p>
<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
<%= link_to 'Edit', edit_plan_event_path(@plan, @event) %>
<%= link_to 'Back', plan_events_path(@plan) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripBeaconApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<!-- app/views/plans/edit.html.erb -->
<h1>Edit Plan</h1>
<%= form_with(model: @plan, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<!-- app/views/plans/index.html.erb -->
<h1>Plans</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.title %></td>
        <td><%= plan.start_date %></td>
        <td><%= plan.end_date %></td>
        <td><%= plan.description %></td>
        <td>
          <%= link_to 'Show', plan %>
          <%= link_to 'Edit', edit_plan_path(plan) %>
          <%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<!-- app/views/plans/new.html.erb -->
<h1>New Plan</h1>
<%= form_with(model: @plan, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<!-- app/views/plans/show.html.erb -->
<h1>Plan</h1>
<p>
  <strong>Title:</strong>
  <%= @plan.title %>
</p>
<p>
  <strong>Start Date:</strong>
  <%= @plan.start_date %>
</p>
<p>
  <strong>End Date:</strong>
  <%= @plan.end_date %>
</p>
<p>
  <strong>Description:</strong>
  <%= @plan.description %>
</p>
<h2>Schedule</h2>
<div class="schedule">
  <% @plan.events_by_date.each do |date, events| %>
    <div class="day">
      <h3><%= date.strftime("%Y-%m-%d") %></h3>
      <ul>
        <% events.each do |event| %>
          <li>
            <strong><%= event.event_type %>:</strong> <%= event.name %>
            <%= event.start_time.strftime("%H:%M") %> - <%= event.end_time.strftime("%H:%M") %>
            <p><%= event.description %></p>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>
<li>
  <%= link_to 'new event', new_event_path %>
</li>
<%= link_to 'Edit', edit_plan_path(@plan) %>
<%= link_to 'Back', plans_path %>